name: build

on:
  push:
    branches:
      - main
      - develop
    paths:
      - src/**
      - include/**
  pull_request:
    branches:
      - main
      - develop
    paths:
      - src/**
      - include/**

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Packages
        run: |
          sudo apt update -qq
          sudo apt install -y nasm

      - name: make
        run: make
