name: build

on:
  push:
    branches:
      - main
      - develop
    paths:
      - src/**
      - include/**
      - Makefile
      - .github/workflows/build.yml

  pull_request:
    branches:
      - main
      - develop
    paths:
      - src/**
      - include/**
      - Makefile
      - .github/workflows/build.yml

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Packages
        run: |
          sudo apt update -qq
          sudo apt install -y nasm

      - name: make
        run: make

      - name: Archive compiled executable
        uses: actions/upload-artifact@v2
        with:
          name: apollon-master
          path: dist/*
